# Grounded-Lane Batch 1: Natur, Tiere, Pflanzen, Wetter-Phaenomene.
# ROWS = [(thema, fakten, user, assistant, lang)], lang "de"/"en".
# fakten = 2-4 Saetze echtes, unstrittiges Allgemeinwissen (keine erfundenen Praezisionszahlen).
ROWS = [
    (
        "Igel im Winterschlaf",
        "Igel halten von Spätherbst bis ins Frühjahr Winterschlaf. Dabei sinkt ihre Körpertemperatur stark ab und Herzschlag sowie Atmung verlangsamen sich enorm, um Energie zu sparen. Sie zehren die ganze Zeit von ihrem im Herbst angefressenen Fettpolster.",
        "Ich hab im Garten einen Igel gefunden, der ganz zusammengerollt und regungslos war. Ist das normal?",
        "Klingt nach Winterschlaf, das ist bei Igeln völlig normal. Herz und Atmung fahren runter, die zehren dann einfach von ihrem Fettpolster vom Herbst. Am besten in Ruhe lassen, der schläft nur ganz tief.",
        "de",
    ),
    (
        "Zugvögel und der Weg nach Süden",
        "Viele Vogelarten wie Schwalben ziehen im Herbst in wärmere Regionen, weil dort mehr Nahrung verfügbar ist. Manche Zugvögel legen dabei mehrere tausend Kilometer zurück. Im Frühjahr kehren sie oft in dieselbe Gegend zurück, in der sie geschlüpft sind.",
        "Wo sind eigentlich die ganzen Schwalben hin, die im Sommer immer am Haus waren?",
        "Die sind längst unterwegs Richtung Süden, wo es mehr zu fressen gibt. Manche schaffen dabei mehrere tausend Kilometer. Im Frühjahr tauchen die meisten wieder genau hier auf, als hätten sie nie weg sein wollen.",
        "de",
    ),
    (
        "Schwänzeltanz der Bienen",
        "Honigbienen teilen ihren Artgenossinnen im Stock durch eine Art Tanzbewegung mit, wo gute Futterquellen liegen. Über Richtung und Länge der Bewegung wird Entfernung und Himmelsrichtung zur Blüte codiert. Diese Verständigung funktioniert komplett im Dunkeln des Bienenstocks.",
        "Wie wissen eigentlich alle Bienen aus einem Volk, wo die guten Blumen stehen?",
        "Eine Kundschafterin tanzt es den anderen vor, mitten im Dunkeln des Stocks. Über die Richtung und wie lang sie tanzt, steckt drin, wo die Blüten sind und wie weit. Eine der klügsten Sprachen, die ich kenne.",
        "de",
    ),
    (
        "Echoortung bei Delfinen",
        "Delfine senden hohe Klicklaute aus und orten anhand des Echos Beute, Hindernisse und andere Tiere. Diese Echoortung funktioniert auch im trüben Wasser, wo Augen kaum etwas erkennen. Delfine leben zudem meist in engen sozialen Gruppen.",
        "Wie finden Delfine eigentlich ihre Beute, wenn das Wasser trüb ist?",
        "Die hören quasi mit den Ohren statt mit den Augen. Sie senden Klicklaute aus und lesen aus dem Echo, was da schwimmt. Funktioniert selbst dann noch, wenn man die eigene Flosse kaum sieht.",
        "de",
    ),
    (
        "Gedächtnis und Familienbindung von Elefanten",
        "Elefanten leben in engen Familienverbänden, angeführt meist von einer erfahrenen älteren Kuh. Sie haben ein bemerkenswert gutes Gedächtnis und können sich an Wasserstellen oder andere Elefanten über Jahre erinnern. Verstorbene Herdenmitglieder scheinen sie wahrzunehmen und verweilen manchmal an deren Überresten.",
        "Stimmt es, dass Elefanten sich wirklich an alles erinnern?",
        "So ganz stimmt der Spruch schon. Sie leben in engen Familien, angeführt von einer erfahrenen Kuh, und merken sich Wasserstellen über Jahre. Sie scheinen sogar zu spüren, wenn ein Herdenmitglied gestorben ist, und bleiben dann einfach bei ihm.",
        "de",
    ),
    (
        "Farbwechsel und Tarnung beim Oktopus",
        "Oktopusse können ihre Hautfarbe und sogar die Struktur ihrer Haut in Sekundenschnelle verändern. Möglich machen das spezielle Pigmentzellen direkt unter der Haut. Damit tarnen sie sich vor Fressfeinden oder passen sich ihrer Umgebung an.",
        "Wie schafft es ein Oktopus, sich einfach unsichtbar zu machen?",
        "Unsichtbar nicht ganz, aber verdammt nah dran. Er hat winzige Pigmentzellen direkt unter der Haut und kann Farbe wie Struktur in Sekunden umschalten. Praktisch ein Umhang aus der eigenen Haut.",
        "de",
    ),
    (
        "Gesang der Wale über weite Strecken",
        "Buckelwale erzeugen komplexe Gesänge, die unter Wasser über sehr lange Strecken tragen können. Man vermutet, dass diese Gesänge der Kommunikation und Partnersuche dienen. Die Gesangsmuster verändern sich über die Jahre und ähneln sich innerhalb einer Population.",
        "Können Wale sich wirklich über riesige Entfernungen hören?",
        "Unter Wasser trägt Schall enorm weit, und Buckelwale nutzen das für ihre langen Gesänge. Man geht davon aus, dass es um Partnersuche und Kontakt geht. Die Melodien wandeln sich sogar über die Jahre, wie ein Ohrwurm, der langsam mutiert.",
        "de",
    ),
    (
        "Arbeitsteilung bei Ameisen",
        "Ameisenvölker organisieren sich in klar verteilten Aufgaben wie Futtersuche, Brutpflege oder Verteidigung des Baus. Über Duftstoffe, sogenannte Pheromone, hinterlassen sie Spuren zu Futterquellen, denen andere Ameisen folgen. Ein Ameisenstaat kann so erstaunlich koordiniert wirken, obwohl kein einzelnes Tier den Überblick hat.",
        "Wie organisieren sich Ameisen eigentlich, ohne dass einer der Chef ist?",
        "Keiner hat den Überblick und trotzdem läuft es wie am Schnürchen. Jede hat ihre Aufgabe, Futter, Brut oder Wache, und Duftspuren zeigen den anderen den Weg zu guten Funden. Aus lauter kleinen Regeln wird ein ziemlich kluges Ganzes.",
        "de",
    ),
    (
        "Echoortung bei Fledermäusen",
        "Fledermäuse orientieren sich in der Dunkelheit über Ultraschalllaute, die sie ausstoßen und deren Echo sie auswerten. Damit erkennen sie Hindernisse und jagen fliegende Insekten im Flug. Ihre Augen funktionieren zusätzlich, sind für die Jagd aber weniger entscheidend.",
        "Wie fliegen Fledermäuse eigentlich nachts, ohne überall gegenzuknallen?",
        "Die verlassen sich nicht auf die Augen, sondern rufen in Ultraschall und lauschen aufs Echo. Damit erkennen sie Wände, Äste und sogar eine Mücke im Flug. Fast wie Sehen, nur mit den Ohren.",
        "de",
    ),
    (
        "Schnurren bei Katzen",
        "Katzen schnurren nicht nur, wenn sie sich wohlfühlen, sondern manchmal auch bei Stress oder Schmerzen. Die Frequenz des Schnurrens liegt in einem Bereich, dem man eine leicht heilungsfördernde Wirkung auf Muskeln und Knochen nachsagt. Der genaue Mechanismus, wie das Schnurren erzeugt wird, ist nicht abschließend geklärt.",
        "Warum schnurrt meine Katze eigentlich, wenn sie beim Tierarzt total gestresst ist?",
        "Schnurren heißt nicht immer nur Wohlfühlen, manche Katzen tun das auch bei Stress. Man vermutet sogar, dass die Frequenz leicht heilsam für Muskeln und Knochen ist.",
        "de",
    ),
    (
        "Magnetfeld-Orientierung bei Zugvögeln",
        "Viele Zugvögel können das Magnetfeld der Erde wahrnehmen und nutzen es zur Orientierung auf ihren langen Flügen. Zusätzlich orientieren sie sich an der Sonne, den Sternen und markanten Landschaften. Wie genau der innere Magnetkompass funktioniert, wird noch erforscht.",
        "Woher wissen Zugvögel eigentlich, wohin sie fliegen müssen?",
        "Die haben quasi einen eingebauten Kompass fürs Erdmagnetfeld. Dazu kommen Sonne, Sterne und markante Landmarken als Wegweiser. Wie genau der innere Kompass tickt, wird tatsächlich noch erforscht, auch für Fachleute bleibt da ein Rest Rätsel.",
        "de",
    ),
    (
        "Leuchten der Glühwürmchen",
        "Glühwürmchen erzeugen ihr Leuchten durch eine chemische Reaktion im Körper, die sogenannte Biolumineszenz. Mit dem Blinken locken sie vor allem Partner zur Paarung an. Verschiedene Arten haben dabei unterschiedliche Blinkmuster.",
        "Wie leuchten Glühwürmchen eigentlich, ohne heiß zu werden?",
        "Das ist eine chemische Reaktion im Körper, kein Feuer, darum bleibt es kühl. Mit dem Blinken werben sie um Partner, und jede Art hat da ihr eigenes Muster. Kleine Lichtsignale, mitten in der Sommernacht.",
        "de",
    ),
    (
        "Eichhörnchen und vergessene Nussverstecke",
        "Eichhörnchen vergraben im Herbst Nüsse und Samen als Wintervorrat an vielen verschiedenen Stellen. Einen Teil dieser Verstecke finden sie später nicht wieder. Aus den vergessenen Nüssen wachsen manchmal neue Bäume.",
        "Erzähl mir was Schönes über Eichhörnchen.",
        "Die vergraben im Herbst überall Nüsse als Vorrat, an ganz vielen Stellen. Nicht alle finden sie später wieder. Aus den vergessenen wächst manchmal ein neuer Baum, ganz ohne dass es so geplant war.",
        "de",
    ),
    (
        "Kommunikation von Bäumen über Pilznetzwerke",
        "Baumwurzeln sind im Boden häufig über feine Pilzfäden miteinander verbunden, ein Netzwerk, das manchmal Wood Wide Web genannt wird. Über dieses Netz können Bäume Nährstoffe austauschen und sich vor Schädlingen warnen. Ältere, größere Bäume unterstützen darüber teils gezielt jüngere Bäume in ihrer Nähe.",
        "Bäume warnen sich gegenseitig, hab ich mal gehört. Stimmt das wirklich?",
        "Ja, über ein Netzwerk aus feinen Pilzfäden im Boden, das manche das Wood Wide Web nennen. Darüber tauschen sie Nährstoffe aus und warnen sich vor Schädlingen. Größere Bäume geben darüber sogar den kleineren in der Nähe etwas ab.",
        "de",
    ),
    (
        "Sonnenblumen und der Sonnenlauf",
        "Junge Sonnenblumen drehen ihre Blütenknospe tagsüber der Sonne nach, ein Verhalten, das Heliotropismus genannt wird. Nachts richten sie sich wieder Richtung Osten aus, um bei Sonnenaufgang bereit zu sein. Ausgewachsene Blüten stellen dieses Nachdrehen meist ein und bleiben nach Osten ausgerichtet.",
        "Drehen sich Sonnenblumen wirklich mit der Sonne mit?",
        "Solange sie jung sind, ja. Tagsüber folgen sie der Sonne, nachts schwenken sie zurück Richtung Osten, bereit für den nächsten Sonnenaufgang. Ausgewachsen bleiben die meisten dann einfach nach Osten stehen.",
        "de",
    ),
    (
        "Berührungsempfindliche Mimose",
        "Die Mimose ist eine Pflanze, deren Blätter sich bei Berührung innerhalb von Sekunden zusammenklappen. Vermutlich schützt sie sich damit vor Fressfeinden, die durch die plötzliche Bewegung abgeschreckt werden. Nach einiger Zeit entfalten sich die Blätter wieder.",
        "Es gibt doch diese Pflanze, die sich zusammenzieht, wenn man sie anfasst, oder?",
        "Die Mimose, genau. Fasst man sie an, klappen die Blätter innerhalb von Sekunden zusammen, vermutlich um Fressfeinde zu erschrecken. Nach einer Weile entfaltet sie sich einfach wieder, als wäre nichts gewesen.",
        "de",
    ),
    (
        "Wasserspeicherung bei Kakteen",
        "Kakteen speichern in ihrem dicken, fleischigen Gewebe große Mengen Wasser, um lange Trockenperioden zu überstehen. Ihre Stacheln sind zu Blättern umgewandelt und verringern die Verdunstungsfläche. Viele Arten überleben so über Monate ganz ohne Regen.",
        "Wie überleben Kakteen eigentlich so lange ohne Wasser?",
        "Die speichern es einfach, in ihrem dicken Gewebe wie in einem Vorratstank. Die Stacheln sind eigentlich umgebaute Blätter, die kaum Wasser verdunsten lassen. Damit kommen manche Arten monatelang ohne einen Tropfen Regen aus.",
        "de",
    ),
    (
        "Farbwechsel des Herbstlaubs",
        "Im Herbst bauen Bäume den grünen Blattfarbstoff Chlorophyll ab, weil sie sich auf den Winter vorbereiten. Dadurch werden andere, vorher überdeckte Farbstoffe wie Gelb- und Orangetöne sichtbar. Manche Blätter bilden zusätzlich rote Farbstoffe neu.",
        "Warum werden die Blätter im Herbst eigentlich bunt?",
        "Die Bäume bauen das grüne Chlorophyll ab, weil der Winter naht. Darunter kommen Gelb- und Orangetöne zum Vorschein, die vorher einfach überdeckt waren. Manche Blätter legen sogar noch frisches Rot nach, wie eine Abschiedsfarbe.",
        "de",
    ),
    (
        "Sauerstoffproduktion durch Bäume",
        "Bäume nehmen über ihre Blätter Kohlendioxid auf und geben durch die Photosynthese Sauerstoff ab. Dieser Prozess läuft vor allem bei Tageslicht ab. Wälder gelten deshalb auch als wichtige Sauerstoffquelle und Kohlenstoffspeicher.",
        "Wie viel Sauerstoff macht so ein Baum eigentlich?",
        "Genaue Zahlen sind da schwierig, aber die Richtung stimmt: über die Blätter nehmen sie Kohlendioxid auf und geben bei Tageslicht Sauerstoff ab. Ein ganzer Wald wird darüber zu einer richtigen Sauerstoffquelle. Ich mag den Gedanken, dass wir davon mitatmen.",
        "de",
    ),
    (
        "Schnelles Wachstum von Bambus",
        "Bambus gehört zu den am schnellsten wachsenden Pflanzen der Welt und kann unter guten Bedingungen mehrere Zentimeter am Tag zulegen. Botanisch zählt er zu den Gräsern, nicht zu den Bäumen. Manche Arten werden dennoch mehrere Meter hoch.",
        "Stimmt es, dass Bambus so wahnsinnig schnell wächst?",
        "Ja, unter guten Bedingungen legt er mehrere Zentimeter am Tag zu, fast wie zusehen. Botanisch ist er übrigens ein Gras, kein Baum, auch wenn er meterhoch wird. So ein bisschen der Underdog unter den Riesen.",
        "de",
    ),
    (
        "Samenverbreitung beim Löwenzahn",
        "Die Pusteblume des Löwenzahns besteht aus vielen kleinen Samen, die jeweils an einem feinen Fallschirm aus Härchen hängen. Wind trägt diese Samen teils über weite Strecken davon. So kann sich die Pflanze auch an neuen Orten ausbreiten.",
        "Warum pustet man eigentlich Pusteblumen weg, gibt's dafür einen Grund?",
        "Jeder Samen hängt an einem winzigen Fallschirm aus Härchen, und der Wind trägt ihn oft weit weg. Wir pusten also eigentlich nur nach, was der Löwenzahn sowieso vorhatte.",
        "de",
    ),
    (
        "Genügsamkeit von Moos",
        "Moos hat keine echten Wurzeln, sondern nimmt Wasser und Nährstoffe direkt über die Oberfläche auf. Es wächst deshalb auch auf Steinen, Baumrinde oder Dächern, wo andere Pflanzen kaum Halt finden. Bei Trockenheit kann es fast vollständig austrocknen und sich später wieder erholen.",
        "Wie schafft es Moos eigentlich, auf einem nackten Stein zu wachsen?",
        "Moos hat gar keine richtigen Wurzeln, es nimmt Wasser einfach über die ganze Oberfläche auf. Deshalb klappt das auch auf Stein oder Dach, wo sonst nichts Halt findet. Bei Trockenheit vertrocknet es fast komplett und erholt sich später einfach wieder.",
        "de",
    ),
    (
        "Kletterhilfe von Efeu",
        "Efeu bildet an seinen Trieben kleine Haftwurzeln, mit denen er sich an Mauern oder Baumstämmen festhält. Er schmarotzt dabei aber nicht am Baum, sondern nutzt ihn nur als Kletterhilfe. Efeu bleibt auch im Winter grün und blüht erst spät im Jahr.",
        "Schadet Efeu eigentlich dem Baum, an dem es hochwächst?",
        "Schmarotzen tut er nicht, er nutzt den Baum nur als Klettergerüst, mit kleinen Haftwurzeln an den Trieben. Grün bleibt er dabei das ganze Jahr über.",
        "de",
    ),
    (
        "Baumringe als Wachstumsgeschichte",
        "Bäume bilden jedes Jahr einen neuen Ring aus Holz, der im Querschnitt des Stammes sichtbar wird. Aus der Anzahl der Ringe lässt sich ablesen, wie viele Jahre der Baum gewachsen ist. Breite oder schmale Ringe verraten zudem, ob es ein gutes oder ein trockenes Jahr für den Baum war.",
        "Kann man an so einem Baumstumpf wirklich ablesen, wie viele Jahre der Baum gewachsen ist?",
        "Ja, jeder Ring steht für ein Jahr, einfach nachzählen. Ob die Ringe breit oder schmal ausfallen, verrät sogar, ob es ein gutes oder ein trockenes Jahr war. Ein Baumstumpf ist quasi ein kleines Tagebuch aus Holz.",
        "de",
    ),
    (
        "Entstehung des Regenbogens",
        "Ein Regenbogen entsteht, wenn Sonnenlicht in feinen Regentropfen gebrochen und in seine Farben zerlegt wird. Dabei wird das Licht im Tropfen einmal reflektiert, wodurch die typische Bogenform entsteht. Man sieht ihn deshalb immer mit dem Rücken zur Sonne.",
        "Wie entsteht eigentlich so ein Regenbogen?",
        "Sonnenlicht bricht sich in winzigen Regentropfen und wird dabei in seine Farben zerlegt. Im Tropfen spiegelt sich das Licht einmal, daher die Bogenform. Und man sieht ihn immer nur mit dem Rücken zur Sonne, praktisch als ihr Gegenüber.",
        "de",
    ),
    (
        "Warum Blitz vor Donner kommt",
        "Bei einem Gewitter entstehen Blitz und Donner nahezu gleichzeitig. Licht breitet sich aber viel schneller aus als Schall, deshalb sieht man den Blitz zuerst und hört den Donner erst etwas später. Aus der Zeitspanne dazwischen lässt sich grob abschätzen, wie weit das Gewitter entfernt ist.",
        "Warum sehe ich den Blitz eigentlich immer, bevor ich den Donner höre?",
        "Beide entstehen fast gleichzeitig, aber Licht ist einfach viel schneller unterwegs als Schall. Darum kommt der Blitz zuerst bei dir an, der Donner hinkt hinterher. Zählt man die Sekunden dazwischen, kriegt man sogar ein Gefühl dafür, wie weit das Gewitter noch weg ist.",
        "de",
    ),
    (
        "Einzigartigkeit von Schneeflocken",
        "Schneeflocken entstehen, wenn Wasserdampf in kalter Luft direkt zu Eiskristallen wird. Ihre genaue Form hängt von Temperatur und Feuchtigkeit auf dem Weg nach unten ab. Weil diese Bedingungen sich winzig unterscheiden, gilt jede Schneeflocke als praktisch einzigartig.",
        "Stimmt es wirklich, dass keine zwei Schneeflocken gleich aussehen?",
        "So gut wie, ja. Sie entstehen, wenn Wasserdampf in kalter Luft direkt zu Eis wird, und die Form hängt von Temperatur und Feuchtigkeit auf dem Weg nach unten ab. Weil sich das ständig minimal ändert, gleicht kaum eine der anderen.",
        "de",
    ),
    (
        "Nebel als bodennahe Wolke",
        "Nebel entsteht, wenn feuchte Luft am Boden so weit abkühlt, dass der Wasserdampf zu winzigen Tröpfchen kondensiert. Im Grunde ist Nebel damit nichts anderes als eine Wolke, die den Boden berührt. Besonders häufig bildet er sich in klaren Nächten und über Gewässern.",
        "Ist Nebel eigentlich sowas wie eine Wolke, die auf dem Boden gelandet ist?",
        "Genau das ist es im Grunde. Kühlt feuchte Luft am Boden weit genug ab, kondensiert der Wasserdampf zu winzigen Tröpfchen. Besonders gern passiert das in klaren Nächten und über Wasser, eine Wolke, die sich verlaufen hat.",
        "de",
    ),
    (
        "Entstehung von Wind",
        "Wind entsteht durch Unterschiede im Luftdruck zwischen verschiedenen Regionen. Luft strömt dabei immer von Gebieten mit hohem zu Gebieten mit niedrigem Druck. Sonneneinstrahlung erwärmt die Luft ungleichmäßig und sorgt so überhaupt erst für diese Druckunterschiede.",
        "Woher kommt eigentlich der Wind, wo entsteht der?",
        "Im Grunde aus Druckunterschieden in der Luft. Wo es warm ist, steigt Luft auf und der Druck sinkt, woanders ist er höher, und die Luft strömt dazwischen aus. Die Sonne heizt eben nicht überall gleich, und der Ausgleich, das ist dann der Wind.",
        "de",
    ),
    (
        "Verschiedene Wolkenarten",
        "Wolken lassen sich grob nach ihrer Höhe und Form unterscheiden, etwa in flache Schichtwolken, aufgetürmte Haufenwolken und hohe, feine Federwolken. Haufenwolken, umgangssprachlich Schäfchenwolken, entstehen oft bei schönem Wetter. Dunkle, mächtige Quellwolken können dagegen Gewitter ankündigen.",
        "Was sind eigentlich diese flauschigen weißen Wolken, die aussehen wie Schäfchen?",
        "Das sind Haufenwolken, umgangssprachlich eben Schäfchenwolken. Die zeigen sich meist bei schönem, ruhigem Wetter. Türmen sie sich dunkel auf, kündigen sie eher ein Gewitter an, dann ist der flauschige Charme schnell vorbei.",
        "de",
    ),
    (
        "Tau am Morgen",
        "Tau entsteht in klaren, windstillen Nächten, wenn sich Oberflächen wie Gras stark abkühlen. Die Luft direkt darüber kühlt mit ab, bis der enthaltene Wasserdampf kondensiert und als kleine Tröpfchen sichtbar wird. Bewölkte Nächte verhindern diese Abkühlung meist, weshalb dort weniger Tau entsteht.",
        "Warum ist morgens manchmal das ganze Gras nass, obwohl es gar nicht geregnet hat?",
        "Das ist Tau, kein Regen. In klaren, ruhigen Nächten kühlt das Gras stark ab, und der Wasserdampf aus der Luft setzt sich darauf als Tröpfchen ab. War die Nacht bewölkt, bleibt es meist trocken.",
        "de",
    ),
    (
        "Entstehung von Hagel",
        "Hagel bildet sich in kräftigen Gewitterwolken, in denen starke Aufwinde Regentropfen immer wieder nach oben tragen. Dort gefrieren sie in großer Höhe und wachsen bei jedem weiteren Durchlauf durch die Wolke. Irgendwann werden die Eiskörner zu schwer und fallen als Hagel zu Boden.",
        "Wie entsteht eigentlich Hagel mitten im Sommer, wenn es doch warm ist?",
        "In kräftigen Gewitterwolken herrschen ganz oben eisige Temperaturen. Starke Aufwinde schleudern Tropfen immer wieder nach oben, wo sie gefrieren und weiterwachsen. Irgendwann sind die Körner zu schwer für den Aufwind und fallen als Hagel runter, mitten im warmen Sommertag.",
        "de",
    ),
    (
        "Föhn als warmer Fallwind",
        "Föhn ist ein warmer, trockener Wind, der entsteht, wenn feuchte Luft an einem Gebirge aufsteigt, dort abregnet und auf der anderen Seite trocken wieder absinkt. Beim Absinken erwärmt sich die Luft deutlich. Föhn tritt besonders häufig in Alpennähe auf und wird manchmal mit Kopfschmerzen in Verbindung gebracht.",
        "Was ist eigentlich dieser Föhn, von dem alle reden, wenn es in den Bergen so warm wird?",
        "Feuchte Luft steigt an einem Gebirge auf, regnet dort ab und sinkt auf der anderen Seite trocken wieder runter. Beim Absinken wird sie richtig warm. Besonders in Alpennähe kennt man das, manche bringen es sogar mit Kopfschmerzen in Verbindung.",
        "de",
    ),
    (
        "Jahreszeiten durch die geneigte Erdachse",
        "Die Erdachse steht schräg zur Umlaufbahn um die Sonne geneigt. Dadurch trifft Sonnenlicht im Jahresverlauf mal steiler, mal flacher auf verschiedene Regionen der Erde. Diese wechselnde Einstrahlung sorgt für die Abfolge der Jahreszeiten.",
        "Warum gibt es eigentlich Jahreszeiten, wieso wird es nicht einfach immer gleich warm?",
        "Die Erdachse steht schräg, nicht gerade zur Sonne. Dadurch trifft das Licht mal steiler, mal flacher auf eine Gegend, je nachdem, wo die Erde gerade auf ihrer Bahn steht. Genau dieser Wechsel macht aus dem Jahr Frühling, Sommer, Herbst und Winter.",
        "de",
    ),
    (
        "Polarlichter durch Sonnenwind",
        "Polarlichter entstehen, wenn geladene Teilchen aus dem Sonnenwind auf die Erdatmosphäre treffen und dort mit Gasteilchen zusammenstoßen. Das Erdmagnetfeld lenkt diese Teilchen bevorzugt zu den Polregionen. Je nach Gas, auf das sie treffen, leuchtet der Himmel dann grünlich oder rötlich.",
        "Wie entstehen eigentlich Polarlichter, dieses grüne Leuchten am Himmel?",
        "Geladene Teilchen aus dem Sonnenwind rauschen auf die Erdatmosphäre zu und stoßen dort mit Gasteilchen zusammen. Das Erdmagnetfeld lenkt sie besonders zu den Polen. Je nachdem, welches Gas sie treffen, leuchtet der Himmel grün oder rötlich, wie ein Feuerwerk der Natur.",
        "de",
    ),
    (
        "Farben beim Sonnenuntergang",
        "Beim Sonnenuntergang legt das Licht einen viel längeren Weg durch die Atmosphäre zurück als tagsüber. Dabei wird blaues Licht auf dem Weg stärker gestreut und herausgefiltert, während rote und orange Farbtöne übrig bleiben. Staub oder Feuchtigkeit in der Luft können die Farben zusätzlich verstärken.",
        "Warum wird der Himmel eigentlich rot und orange, wenn die Sonne untergeht?",
        "Weil das Licht dann einen viel längeren Weg durch die Luft nehmen muss. Blaue Anteile werden dabei unterwegs rausgefiltert, rot und orange bleiben übrig. Staub oder Feuchtigkeit in der Luft können das Farbschauspiel sogar noch kräftiger machen.",
        "de",
    ),
    (
        "Ebbe und Flut durch Mondanziehung",
        "Ebbe und Flut entstehen vor allem durch die Anziehungskraft des Mondes auf das Wasser der Meere. Auf der mondzugewandten Seite der Erde wird das Wasser dadurch angehoben, auf der abgewandten Seite passiert aus anderen Gründen ähnliches. Die Sonne trägt mit ihrer eigenen Anziehungskraft zusätzlich etwas dazu bei.",
        "Wieso gibt es eigentlich Ebbe und Flut, was zieht das Wasser hin und her?",
        "Vor allem der Mond, mit seiner Anziehungskraft auf das Wasser. Auf der Seite, die ihm zugewandt ist, wölbt sich das Meer etwas nach oben, auf der gegenüberliegenden Seite passiert aus anderen Gründen ähnliches. Die Sonne mischt mit ihrer eigenen Anziehung noch ein bisschen mit.",
        "de",
    ),
    (
        "Warum das Meer salzig ist",
        "Flüsse lösen beim Fließen über Gestein winzige Mengen an Mineralien und Salzen und tragen sie ins Meer. Weil aus dem Meer nur Wasser verdunstet, die Salze aber bleiben, reichern sie sich über sehr lange Zeiträume an. So ist das Meer heute deutlich salziger als jeder Fluss.",
        "Warum ist das Meer eigentlich salzig und Flüsse nicht?",
        "Flüsse lösen auf ihrem Weg winzige Mengen Salz und Mineralien aus dem Gestein und tragen sie ins Meer. Verdunsten tut dort aber nur das Wasser, die Salze bleiben zurück. Über sehr lange Zeit sammelt sich davon einfach immer mehr an.",
        "de",
    ),
    (
        "Wald als Lebensraum",
        "Ein Wald ist mehr als eine Ansammlung von Bäumen, er ist Lebensraum für unzählige Tier-, Pilz- und Pflanzenarten. Verschiedene Schichten von Boden bis Baumkrone bieten dabei ganz unterschiedliche Bedingungen. Totholz spielt darin eine wichtige Rolle, weil viele Insekten und Pilze davon leben.",
        "Ist ein Wald eigentlich nur eine Ansammlung von Bäumen, oder steckt da mehr dahinter?",
        "Viel mehr. Vom Boden bis zur Baumkrone bietet er ganz unterschiedliche Lebensräume für Tiere, Pilze und Pflanzen. Sogar totes Holz hat seinen Platz darin, weil unzählige Insekten und Pilze genau davon leben.",
        "de",
    ),
    (
        "Vulkane formen neues Land",
        "Bei einem Vulkanausbruch tritt geschmolzenes Gestein aus dem Erdinneren an die Oberfläche. Erkaltet dieses Gestein, entsteht daraus neues, oft sehr fruchtbares Land. Manche Inseln sind auf diese Weise überhaupt erst durch Vulkantätigkeit entstanden.",
        "Können Vulkane wirklich komplett neues Land schaffen?",
        "Ja, tatsächlich. Geschmolzenes Gestein tritt aus und erkaltet an der Oberfläche zu neuem Land, das oft sogar richtig fruchtbar ist. Manche Inseln verdanken ihre Existenz komplett solchen Ausbrüchen. Aus Feuer wird also mit der Zeit fester Boden.",
        "de",
    ),
    (
        "Trockenheit in Wüsten",
        "Wüsten zeichnen sich vor allem durch sehr geringe Niederschlagsmengen aus, nicht zwingend durch Hitze. Manche Wüsten sind sogar kalt, wie große Teile der Antarktis, die nach dieser Definition ebenfalls als Wüste gilt. Pflanzen und Tiere dort haben sich oft auf extreme Wassersparsamkeit spezialisiert.",
        "Ist eine Wüste eigentlich immer heiß, oder gibt's auch kalte?",
        "Nicht zwingend heiß, entscheidend ist einfach wenig Niederschlag. Sogar große Teile der Antarktis gelten nach der Definition als Wüste, so kalt sie auch ist. Tiere und Pflanzen dort haben sich vor allem aufs Wassersparen spezialisiert, egal bei welcher Temperatur.",
        "de",
    ),
    (
        "Gletscher als Süßwasserspeicher",
        "Gletscher bestehen aus über lange Zeit verdichtetem Schnee und Eis und speichern große Mengen an Süßwasser. Sie bewegen sich unter ihrem eigenen Gewicht extrem langsam talwärts. Schmelzwasser aus Gletschern speist in vielen Regionen wichtige Flüsse.",
        "Was ist eigentlich ein Gletscher genau, einfach nur viel Schnee?",
        "Mehr als das, es ist über lange Zeit verdichteter Schnee und Eis, der riesige Mengen Süßwasser speichert. Unter seinem eigenen Gewicht rutscht er ganz langsam talwärts. Sein Schmelzwasser speist in vielen Gegenden die wichtigsten Flüsse.",
        "de",
    ),
    (
        "Flüsse und ihr Weg zum Meer",
        "Flüsse folgen dem Gefälle der Landschaft und fließen deshalb fast immer von höher gelegenen Regionen Richtung Meer. Auf ihrem Weg sammeln sie Wasser aus vielen kleineren Bächen und Nebenflüssen. Unterwegs formen sie die Landschaft, indem sie Gestein abtragen und Sediment ablagern.",
        "Warum fließen Flüsse eigentlich immer irgendwann ins Meer?",
        "Sie folgen einfach dem Gefälle der Landschaft, von oben nach unten, und das Meer liegt fast immer am tiefsten Punkt. Unterwegs sammeln sie Wasser aus kleineren Bächen ein und formen dabei sogar die Landschaft, sie tragen Gestein ab und lagern es woanders wieder an.",
        "de",
    ),
    (
        "Korallenriffe als Bauwerk winziger Lebewesen",
        "Korallenriffe werden von winzigen Lebewesen, den Korallenpolypen, aus Kalk aufgebaut, die in riesigen Kolonien zusammenleben. Über sehr lange Zeiträume wachsen daraus ganze Riffe. Diese Riffe bieten unzähligen Meerestieren Lebensraum und gelten als besonders artenreiche Ökosysteme.",
        "Sind Korallenriffe eigentlich Pflanzen oder Steine oder was genau?",
        "Eigentlich Tiere, winzige Polypen, die in riesigen Kolonien zusammenleben und Kalk absondern. Über sehr lange Zeit wächst daraus das ganze Riff. Für unzählige andere Meerestiere wird daraus ein richtiges Zuhause, eines der artenreichsten überhaupt.",
        "de",
    ),
    (
        "Artenvielfalt im Regenwald",
        "Tropische Regenwälder beherbergen einen sehr großen Anteil der weltweiten Pflanzen- und Tierarten, obwohl sie nur einen kleinen Teil der Landfläche der Erde bedecken. Das feuchtwarme Klima und die vielen Vegetationsschichten bieten dabei besonders viele unterschiedliche Lebensräume. Viele Arten dort sind bis heute nicht vollständig erforscht.",
        "Warum leben eigentlich in Regenwäldern so unfassbar viele verschiedene Arten?",
        "Obwohl sie nur einen kleinen Teil der Erde bedecken, stecken darin unfassbar viele Arten. Das feuchtwarme Klima und die vielen Schichten von Boden bis Kronendach schaffen einfach jede Menge unterschiedliche Nischen. Manche Arten dort sind bis heute nicht mal richtig erforscht.",
        "de",
    ),
    # --- EN (~10) ---
    (
        "Hedgehogs hibernating",
        "Hedgehogs hibernate from late autumn through early spring to survive the cold months when food is scarce. During hibernation their body temperature drops sharply and their heartbeat slows way down to save energy. They live off fat reserves built up by eating well in autumn.",
        "Do hedgehogs really sleep through the whole winter?",
        "Pretty much, yes. Their temperature drops and their heartbeat slows right down to save energy, living off the fat they packed on in autumn.",
        "en",
    ),
    (
        "How rainbows form",
        "A rainbow forms when sunlight enters raindrops and bends as it passes through, splitting into its different colors. The light reflects once inside each droplet, which is why rainbows appear as an arc. You only see a rainbow with the sun behind you.",
        "What actually makes a rainbow appear?",
        "Sunlight bends as it enters tiny raindrops and splits into its colors. It bounces once inside each drop, and that bounce is what gives you the arc shape. You only ever see one with the sun at your back, like it's following you.",
        "en",
    ),
    (
        "Silent flight of owls",
        "Owls have soft, fringed feather edges that break up the air moving over their wings and reduce turbulence. This lets them fly almost silently compared to most other birds. Silent flight helps them sneak up on prey and also hear better while hunting.",
        "Why can owls fly so quietly compared to other birds?",
        "Their feathers have soft, fringed edges that break up the air instead of letting it rush over smoothly, and that's what kills the noise. Handy for sneaking up on dinner, and it means they can actually hear their prey too.",
        "en",
    ),
    (
        "Autumn leaves changing color",
        "In autumn, trees break down the green pigment chlorophyll as they prepare for winter. This reveals yellow and orange pigments that were already in the leaf but hidden by the green all summer. Some trees also produce new red pigments as the leaves change.",
        "Why do leaves change color in the fall?",
        "Trees break down the green chlorophyll as winter gets closer. Underneath, yellow and orange were there all along, just hidden by the green. Some trees even brew up fresh red as a kind of farewell color.",
        "en",
    ),
    (
        "Thunder following lightning",
        "Lightning and thunder happen at almost the same instant during a storm. Light travels far faster than sound, so you see the flash before you hear the rumble that follows it. Counting the seconds between them gives a rough sense of how far away the storm is.",
        "Why do I always see lightning before I hear the thunder?",
        "They actually happen at almost the same moment, light just gets to you much faster than sound does. So the flash arrives first, the rumble trails behind. Count the seconds in between and you get a rough idea how far off the storm still is.",
        "en",
    ),
    (
        "Bees communicating through dance",
        "Honeybees tell each other where to find good flowers through a movement called the waggle dance, performed inside the dark hive. The direction and length of the dance encode the distance and direction to the food source. This lets a whole colony act on one bee's discovery.",
        "How do bees actually tell each other where the flowers are?",
        "One bee dances it out for the others, right there in the dark hive. The direction and how long she waggles tells the rest how far to fly and which way. One good find, and suddenly the whole colony knows about it.",
        "en",
    ),
    (
        "Whale songs traveling far",
        "Humpback whales produce long, complex songs that can carry across great distances underwater. These songs are thought to play a role in communication and finding mates. The patterns of a song can shift gradually over years and tend to be shared within a population.",
        "Can whales really hear each other from miles and miles away?",
        "Sound travels a long way underwater, and humpback whales put that to good use with their songs. They're thought to help with finding mates and staying in touch. The tunes even drift and change over the years, like a slow-motion trend passing through the pod.",
        "en",
    ),
    (
        "Cacti storing water",
        "Cacti store large amounts of water in their thick, fleshy tissue to survive long dry periods. Their spines are actually modified leaves, which cuts down the surface area that would otherwise lose water to evaporation. Many species can go months without any rain at all.",
        "How do cacti survive so long without any water?",
        "They stockpile it, right in that thick, fleshy body of theirs. Those spines are actually old leaves, shrunk down so barely any water evaporates through them. Some manage months without a drop of rain.",
        "en",
    ),
    (
        "Trees releasing oxygen",
        "Trees take in carbon dioxide through their leaves and release oxygen as part of photosynthesis. This process mainly happens during daylight hours. Forests are therefore considered important sources of oxygen and major stores of carbon.",
        "Do trees really make the oxygen we breathe?",
        "A good share of it, yes. They pull in carbon dioxide through their leaves and let out oxygen while the sun's up, that's photosynthesis doing its quiet work. A whole forest turns into a proper oxygen source. Nice to think we're sharing breath with the trees outside.",
        "en",
    ),
    (
        "Snowflakes being unique",
        "Snowflakes form when water vapor freezes directly into ice crystals inside cold clouds. The exact shape depends on the temperature and humidity the crystal passes through on its way down. Because those conditions vary slightly for every flake, each one ends up essentially unique.",
        "Is it really true that no two snowflakes are ever the same?",
        "Pretty much, yes. They form when water vapor freezes straight into ice crystals, and the shape depends on the temperature and moisture on the way down. Since those conditions shift slightly every time, you basically never get two alike.",
        "en",
    ),
]
