# Grounded-Lane Batch 3: Astronomie, Erde/Geografie-Basics, Physik im Alltag, Zeit/Kalender.
# ROWS = [(thema, fakten, user, assistant, lang)], lang "de"/"en".
ROWS = [
    # --- Astronomie ---
    ("Sonne",
     "Die Sonne ist ein Stern und macht über 99 Prozent der gesamten Masse im Sonnensystem aus. Ihr Licht braucht rund acht Minuten bis zur Erde. Im Kern herrschen Temperaturen von mehreren Millionen Grad.",
     "Wie heiß ist die Sonne eigentlich?",
     "Im Kern brutzelt es bei mehreren Millionen Grad, das lässt sich kaum vorstellen. Und das bisschen Licht, das bei uns ankommt, war davor acht Minuten unterwegs.",
     "de"),
    ("Mond",
     "Der Mond zeigt der Erde wegen gebundener Rotation immer dieselbe Seite. Er entfernt sich jedes Jahr um etwa vier Zentimeter von der Erde. Er ist der einzige Himmelskörper außer der Erde, auf dem schon Menschen gestanden haben.",
     "Sehen wir eigentlich immer dieselbe Mondseite?",
     "Ja, immer dieselbe. Der Mond dreht sich genau im Takt seiner Umlaufbahn, deshalb bleibt uns die Rückseite ewig verborgen. Und ganz nebenbei driftet er jedes Jahr ein Stück weiter weg.",
     "de"),
    ("Planeten",
     "Unser Sonnensystem hat acht Planeten, Merkur der Sonne am nächsten, Neptun am weitesten. Pluto zählt seit 2006 offiziell nur noch als Zwergplanet.",
     "Wie viele Planeten hat unser Sonnensystem eigentlich?",
     "Acht, von Merkur ganz innen bis Neptun ganz außen. Pluto wurde 2006 aus dem Kreis der großen Planeten rausgestuft, was ihm bis heute manche übel nehmen.",
     "de"),
    ("Saturnringe",
     "Saturns Ringe bestehen hauptsächlich aus Eis- und Gesteinsbrocken, viele davon nicht größer als ein Auto. Trotz hunderttausenden Kilometern Durchmesser sind sie im Schnitt erstaunlich dünn, oft nur wenige zehn Meter.",
     "Woraus bestehen eigentlich die Ringe vom Saturn?",
     "Aus Eis- und Gesteinsbrocken, die meisten nicht größer als ein Auto. Verrückt daran: Bei dieser gewaltigen Breite sind sie im Schnitt nur wenige zehn Meter dick.",
     "de"),
    ("Venus",
     "Venus ist trotz größerer Sonnennähe des Merkur der heißeste Planet im Sonnensystem, mit Oberflächentemperaturen von etwa 460 Grad. Grund ist ihre dichte Kohlendioxid-Atmosphäre, die wie ein Treibhaus wirkt.",
     "Welcher Planet ist eigentlich am heißesten?",
     "Die Venus, nicht Merkur, obwohl der der Sonne näher ist. Ihre dicke Wolkendecke hält die Wärme fest wie ein Deckel auf dem Topf, etwa 460 Grad im Schnitt.",
     "de"),
    ("Mars",
     "Mars wirkt rötlich, weil sein Gestein reich an Eisenoxid ist, im Grunde Rost. Er hat mit Olympus Mons den höchsten bekannten Vulkan im Sonnensystem, etwa zweieinhalbmal so hoch wie der Mount Everest.",
     "Warum ist der Mars eigentlich rot?",
     "Weil sein Boden voller Rost steckt, ganz simpel gesagt verrostetes Eisen. Und obendrauf trägt er den höchsten Vulkan im ganzen Sonnensystem.",
     "de"),
    ("Sternschnuppen",
     "Sternschnuppen sind meist winzige Staubkörnchen, die beim Eintritt in die Erdatmosphäre verglühen. Die Leuchtspur entsteht durch Reibungshitze in großer Höhe, oft über 80 Kilometer.",
     "Was ist eigentlich eine Sternschnuppe?",
     "Nur ein Staubkorn, das in unsere Atmosphäre rast und vor Reibung aufleuchtet. Klein und flüchtig, aber genau das macht sie so schön.",
     "de"),
    ("Lichtjahr",
     "Ein Lichtjahr ist keine Zeit-, sondern eine Entfernungsangabe: die Strecke, die Licht in einem Jahr zurücklegt, knapp zehn Billionen Kilometer. Licht ist mit rund 300.000 Kilometern pro Sekunde das schnellste bekannte Ding im Universum.",
     "Was ist eigentlich ein Lichtjahr?",
     "Trotz dem Namen keine Zeit, sondern eine Strecke, die Distanz, die Licht in einem Jahr schafft. Bei 300.000 Kilometern pro Sekunde kommt da eine ziemlich absurde Zahl zusammen.",
     "de"),
    ("Milchstraße",
     "Die Milchstraße ist unsere Heimatgalaxie mit geschätzt hundert bis vierhundert Milliarden Sternen. Sie hat eine Spiralform, und unser Sonnensystem sitzt in einem ihrer äußeren Arme.",
     "Wie viele Sterne hat unsere Galaxie eigentlich?",
     "Schätzungen sagen hundert bis vierhundert Milliarden, so genau weiß das keiner. Und wir sitzen nicht mal in der Mitte, sondern eher am Rand, in einem der Spiralarme.",
     "de"),
    ("Polarstern",
     "Der Polarstern steht fast genau über der verlängerten Erdachse am Nordpol, deshalb scheint er am Nachthimmel kaum seine Position zu verändern. Seefahrer nutzten ihn jahrhundertelang zur Orientierung.",
     "Warum bewegt sich der Polarstern eigentlich kaum am Himmel?",
     "Weil er fast genau über unserer Erdachse steht, während sich alles andere um ihn dreht. Kein Wunder, dass Seefahrer sich jahrhundertelang an ihm festgehalten haben.",
     "de"),
    ("Schwarzes Loch",
     "Ein Schwarzes Loch hat eine so starke Schwerkraft, dass ihm nicht einmal Licht entkommen kann. Es entsteht oft, wenn ein sehr massereicher Stern am Ende seines Lebens in sich zusammenstürzt.",
     "Was ist eigentlich ein Schwarzes Loch?",
     "Ein Ort mit so viel Schwerkraft, dass selbst Licht nicht mehr rauskommt. Meistens der letzte Akt eines riesigen Sterns, der in sich zusammenfällt.",
     "de"),
    ("Sonnenfinsternis",
     "Bei einer Sonnenfinsternis schiebt sich der Mond genau zwischen Erde und Sonne. Das funktioniert nur, weil Mond und Sonne von der Erde aus zufällig fast gleich groß erscheinen, obwohl die Sonne viel größer, aber auch viel weiter weg ist.",
     "Wie kann der kleine Mond eigentlich die riesige Sonne verdecken?",
     "Reiner Zufall der Perspektive: Die Sonne ist gewaltig größer, aber auch viel weiter weg, sodass beide von hier aus fast gleich groß wirken. Ich finde, das ist einer der schönsten Zufälle am Himmel.",
     "de"),
    ("Jupiter",
     "Jupiter is the largest planet in the solar system, more than eleven times wider than Earth. Its famous Great Red Spot is a giant storm that has raged for centuries, and it has more than ninety known moons.",
     "Which planet is actually the biggest?",
     "Jupiter, by a wide margin, more than eleven Earths could fit across it side by side. It even carries its own storm that's been raging for centuries, the Great Red Spot.",
     "en"),
    ("Moon phases",
     "Moon phases happen because we see different portions of the Moon's sunlit half as it orbits Earth, a cycle of about 29.5 days. The Moon produces no light of its own, it only reflects sunlight.",
     "Why does the moon keep changing shape?",
     "It's not actually changing, just showing us more or less of its sunlit side as it circles us. The whole cycle takes about 29 and a half days, and the moon never glows on its own, it only borrows the sun's light.",
     "en"),
    ("Milky Way orbit",
     "Earth sits in one of the outer spiral arms of the Milky Way galaxy. Our solar system takes roughly 230 million years to complete one full orbit around the galactic center.",
     "How long does it take the sun to circle the galaxy?",
     "About 230 million years for one full lap around the galactic center. Makes a human lifetime feel wonderfully small.",
     "en"),

    # --- Erde / Geografie-Basics ---
    ("Erdumfang",
     "Die Erde hat am Äquator einen Umfang von rund 40.075 Kilometern. Sie ist keine perfekte Kugel, sondern am Äquator leicht ausgebeult, eine Folge ihrer eigenen Drehung.",
     "Wie groß ist die Erde eigentlich?",
     "Am Äquator misst sie rund 40.075 Kilometer im Umfang. Und weil sie sich dreht, ist sie dort auch ein bisschen ausgebeult, keine perfekte Kugel.",
     "de"),
    ("Kontinente",
     "Üblicherweise zählt man sieben Kontinente: Afrika, Asien, Europa, Nordamerika, Südamerika, Australien und Antarktis. Manche Modelle fassen Europa und Asien als Eurasien zusammen.",
     "Wie viele Kontinente gibt es eigentlich?",
     "Meistens zählt man sieben. Manche Geografen packen Europa und Asien aber auch als Eurasien zusammen, dann werden es nur sechs. Kommt drauf an, wen man fragt.",
     "de"),
    ("Ozeane",
     "Rund 70 Prozent der Erdoberfläche sind von Wasser bedeckt, größtenteils von den Ozeanen. Der Pazifik ist mit Abstand der größte und tiefste von ihnen.",
     "Wie viel von der Erde ist eigentlich Wasser?",
     "Etwa 70 Prozent, wir leben eigentlich auf einem Wasserplaneten mit ein bisschen Land drauf. Und der Pazifik allein ist größer als alle Kontinente zusammen.",
     "de"),
    ("Mount Everest",
     "Der Mount Everest im Himalaya ist mit knapp 8.849 Metern der höchste Berg der Erde über dem Meeresspiegel. Er wächst durch die Kollision der Kontinentalplatten sogar noch minimal weiter.",
     "Welcher Berg ist eigentlich der höchste der Welt?",
     "Der Mount Everest, knapp 8.849 Meter hoch. Und er ist noch nicht fertig, die Platten darunter schieben ihn Jahr für Jahr ein winziges Stück höher.",
     "de"),
    ("Marianengraben",
     "Der Marianengraben im Pazifik ist mit fast 11.000 Metern die tiefste bekannte Stelle der Erde. Dort herrscht ein Druck, der die meisten Materialien zerdrücken würde, wenn sie nicht speziell dafür gebaut sind.",
     "Wo ist eigentlich die tiefste Stelle im Meer?",
     "Der Marianengraben im Pazifik, fast 11.000 Meter runter. Da unten würde uns der Druck augenblicklich zerdrücken, kein Ort für einen Ausflug.",
     "de"),
    ("längster Fluss",
     "Nil und Amazonas gelten je nach Messmethode als längster Fluss der Erde, beide um die 6.400 bis 6.800 Kilometer. Der Amazonas führt dabei mit Abstand die größte Wassermenge.",
     "Welcher Fluss ist eigentlich der längste der Welt?",
     "Nil oder Amazonas, je nachdem wie man misst, beide liegen um die 6.500 Kilometer. Wassermenge gewinnt aber klar der Amazonas, der führt mehr als alle anderen Flüsse zusammen.",
     "de"),
    ("Plattentektonik",
     "Die Erdkruste besteht aus mehreren großen Platten, die sich langsam bewegen, oft nur wenige Zentimeter im Jahr, etwa so schnell wie Fingernägel wachsen. Erdbeben und Vulkane entstehen häufig an ihren Rändern.",
     "Warum gibt es eigentlich Erdbeben?",
     "Weil unter uns riesige Platten langsam gegeneinander schieben, ungefähr im Tempo von wachsenden Fingernägeln. Meistens ruckelt es genau an den Rändern dieser Platten.",
     "de"),
    ("Erdkern",
     "Der innere Erdkern besteht hauptsächlich aus Eisen und Nickel und ist trotz mehrerer tausend Grad wegen des enormen Drucks fest. Der äußere Kern ist dagegen flüssig, seine Bewegung erzeugt das Erdmagnetfeld.",
     "Was ist eigentlich im Erdinneren?",
     "Ganz innen ein fester Kern aus Eisen und Nickel, trotz mehreren tausend Grad hält ihn der Druck fest zusammen. Drumherum fließt eine flüssige Schicht, und die erzeugt praktischerweise gleich unser Magnetfeld.",
     "de"),
    ("Erdatmosphäre",
     "Die Erdatmosphäre besteht zu rund 78 Prozent aus Stickstoff und nur etwa 21 Prozent aus Sauerstoff. Sie wird mit zunehmender Höhe dünner und geht ohne feste Grenze allmählich ins Weltall über.",
     "Woraus besteht eigentlich die Luft, die wir atmen?",
     "Größtenteils aus Stickstoff, etwa 78 Prozent, Sauerstoff macht nur rund ein Fünftel aus. Klingt nach wenig, reicht uns aber offensichtlich völlig.",
     "de"),
    ("Sahara",
     "Die Sahara ist mit rund neun Millionen Quadratkilometern die größte heiße Wüste der Erde, fast so groß wie die USA. Nachts kann es dort trotz Tageshitze empfindlich kalt werden, weil der Sand die Wärme kaum speichert.",
     "Wie groß ist eigentlich die Sahara?",
     "Ungefähr neun Millionen Quadratkilometer, fast so groß wie die gesamten USA. Und nachts wird es dort erstaunlich kalt, der Sand hält die Tageswärme einfach nicht fest.",
     "de"),
    ("Amazonas-Regenwald",
     "Der Amazonas-Regenwald ist der größte zusammenhängende Regenwald der Erde und wird oft die grüne Lunge des Planeten genannt, weil er große Mengen Kohlendioxid bindet. Er beherbergt einen erheblichen Teil aller bekannten Tier- und Pflanzenarten.",
     "Warum ist der Regenwald eigentlich so wichtig?",
     "Weil er wie ein riesiger Speicher wirkt, der gewaltige Mengen Kohlendioxid bindet, deshalb der Spitzname grüne Lunge. Und ein erheblicher Teil aller bekannten Arten wohnt nirgendwo sonst.",
     "de"),
    ("Gezeiten",
     "Ebbe und Flut entstehen vor allem durch die Anziehungskraft des Mondes auf die Weltmeere. Wenn Sonne und Mond in einer Linie stehen, verstärken sich die Gezeiten zu besonders hohen Springfluten.",
     "Warum gibt es eigentlich Ebbe und Flut?",
     "Der Mond zieht am Wasser, ganz sanft, aber spürbar, das ist im Grunde die ganze Geschichte. Stehen Sonne und Mond dann noch in einer Linie, wird die Flut besonders hoch.",
     "de"),
    ("Tallest waterfall",
     "Angel Falls in Venezuela is the world's tallest waterfall, with a drop of about 979 meters. The water falls so far that much of it turns to mist before ever reaching the ground.",
     "What's the tallest waterfall in the world?",
     "Angel Falls in Venezuela, dropping about 979 meters. Half of it turns to mist on the way down, it never even reaches the ground as actual water.",
     "en"),

    # --- Physik im Alltag ---
    ("Himmel blau",
     "Der Himmel wirkt blau, weil Luftmoleküle blaues Licht aus dem Sonnenlicht stärker streuen als rotes. Das nennt man Rayleigh-Streuung, benannt nach dem Physiker, der das Phänomen beschrieb.",
     "Warum ist der Himmel eigentlich blau?",
     "Weil die Luft blaues Licht viel stärker in alle Richtungen streut als rotes. Deshalb kommt von überall am Himmel blaues Licht bei uns an, nicht nur direkt von der Sonne.",
     "de"),
    ("Regenbogen",
     "Ein Regenbogen entsteht, wenn Sonnenlicht in Regentropfen gebrochen und in seine Farben zerlegt wird. Jeder Tropfen wirkt dabei wie ein winziges Prisma.",
     "Wie entsteht eigentlich ein Regenbogen?",
     "Jeder einzelne Regentropfen bricht das Sonnenlicht wie ein winziges Prisma und zerlegt es in seine Farben. Millionen davon gleichzeitig, und wir sehen einen Bogen.",
     "de"),
    ("Gewitter-Abstand",
     "Licht ist praktisch sofort da, Schall braucht dagegen rund drei Sekunden pro Kilometer. Zählt man die Sekunden zwischen Blitz und Donner und teilt durch drei, bekommt man die ungefähre Entfernung des Gewitters in Kilometern.",
     "Wie weit weg ist eigentlich ein Gewitter, wenn man Blitz und Donner zählt?",
     "Sekunden zwischen Blitz und Donner zählen und durch drei teilen, dann hast du die Kilometer bis zum Gewitter. Das Licht ist eben quasi sofort da, der Schall trödelt hinterher.",
     "de"),
    ("Eis schwimmt",
     "Eis schwimmt auf Wasser, weil es sich beim Gefrieren ausdehnt und dadurch leichter wird als flüssiges Wasser gleichen Volumens. Die meisten anderen Stoffe werden beim Erstarren dichter, nicht leichter.",
     "Warum schwimmt Eis eigentlich auf Wasser?",
     "Wasser macht beim Gefrieren eine Ausnahme, es dehnt sich aus statt sich zusammenzuziehen, und wird dadurch leichter. Die meisten anderen Stoffe machen es genau andersrum.",
     "de"),
    ("Auftrieb Schiffe",
     "Große Schiffe aus Stahl schwimmen, weil ihr Gewicht über den ganzen Rumpf auf ein großes Wasservolumen verteilt wird. Entscheidend ist die Dichte des gesamten Schiffs inklusive der Luft darin, nicht das Material allein.",
     "Wie können eigentlich so schwere Schiffe schwimmen?",
     "Weil im Inneren viel Luft steckt und sich das Gewicht über eine riesige Rumpffläche verteilt. Nicht der Stahl allein zählt, sondern wie dicht das ganze Schiff im Schnitt ist.",
     "de"),
    ("Kompass",
     "Ein Kompass funktioniert, weil die Erde selbst ein riesiges Magnetfeld erzeugt, mit Polen nahe den geografischen Polen. Die Kompassnadel richtet sich einfach entlang dieser unsichtbaren Feldlinien aus.",
     "Warum zeigt ein Kompass eigentlich immer nach Norden?",
     "Die ganze Erde ist im Grunde ein riesiger Magnet, und die Nadel folgt bloß ihren unsichtbaren Feldlinien. Ein bisschen wie ein sehr geduldiger, sehr zuverlässiger Wegweiser.",
     "de"),
    ("Flugzeug fliegen",
     "Flugzeugtragflächen sind oben stärker gewölbt als unten, wodurch die Luft dort schneller strömt und der Druck sinkt. Zusammen mit dem Anstellwinkel der Tragfläche entsteht so genug Auftrieb, um das Gewicht der Maschine zu tragen.",
     "Wie schafft es ein Flugzeug eigentlich abzuheben?",
     "Die Tragflächen sind oben gewölbter, die Luft strömt dort schneller, der Druck sinkt, und schon entsteht Auftrieb. Bei genug Tempo trägt das ein ganzes Flugzeug, jedes Mal wieder ein kleines Wunder.",
     "de"),
    ("Reibung",
     "Reibung wandelt Bewegungsenergie in Wärme um, deshalb werden sich reibende Flächen warm, etwa Handflächen beim Aneinanderreiben. Ganz ohne Reibung könnten wir übrigens auch nicht laufen, sie gibt den Schuhen erst Halt.",
     "Warum werden die Hände eigentlich warm, wenn man sie aneinander reibt?",
     "Die Bewegung wird einfach in Wärme umgewandelt, das ist Reibung in Reinform. Und ganz ohne sie könntest du übrigens nicht mal laufen, dann würden die Füße einfach wegrutschen.",
     "de"),
    ("Schwerkraft",
     "Ohne Luftwiderstand fallen alle Gegenstände gleich schnell, unabhängig von ihrem Gewicht, das zeigte schon Galileo. In echter Luft bremsen leichte, große Objekte wie Federn dagegen deutlich stärker ab.",
     "Fällt ein schwerer Gegenstand eigentlich schneller als ein leichter?",
     "Ohne Luft drumherum: nein, beide fallen exakt gleich schnell, das hat schon Galileo gezeigt. Nur die Luft bremst leichte, sperrige Dinge wie eine Feder viel stärker aus.",
     "de"),
    ("Statische Elektrizität",
     "Statische Elektrizität entsteht, wenn durch Reibung Elektronen von einer Oberfläche auf eine andere übergehen, zum Beispiel beim Ausziehen eines Pullovers. Der kleine Knister-Funke gleicht diese Ladungsunterschiede einfach aus.",
     "Warum knistert es eigentlich manchmal beim Pulli-Ausziehen?",
     "Beim Reiben wandern Elektronen von einer Oberfläche zur anderen, und irgendwann gleicht sich das mit einem kleinen Funken wieder aus. Genau das ist das Knistern, ein winziger Ladungsausgleich.",
     "de"),
    ("Trägheit",
     "Trägheit sorgt dafür, dass ein Körper seinen Bewegungszustand beibehalten will, bis eine Kraft ihn ändert. Deshalb werden wir beim starken Bremsen im Auto nach vorne gedrückt, während der Gurt uns eigentlich zurückhält.",
     "Warum wird man eigentlich nach vorne gedrückt, wenn das Auto stark bremst?",
     "Dein Körper will einfach weiter geradeaus, so wie er es gerade tat, das ist Trägheit. Nur der Gurt überzeugt ihn davon, doch lieber im Auto zu bleiben.",
     "de"),
    ("Mirror",
     "A mirror works because light hits its smooth, metal-coated surface and bounces back almost perfectly instead of scattering. That clean reflection is why the image stays sharp instead of blurring.",
     "How does a mirror actually work?",
     "Light hits that smooth metal coating and bounces straight back instead of scattering everywhere. That's the whole trick, no scattering means a sharp reflection instead of a blur.",
     "en"),
    ("Why metal feels cold",
     "Metal isn't actually colder than wood at room temperature, it just conducts heat away from your hand much faster. That fast heat transfer is what your skin reads as cold, even though a thermometer would show both objects at the same temperature.",
     "Why does metal always feel colder than wood?",
     "Same room, same temperature, but metal pulls the warmth out of your hand much faster than wood does. Your skin just reads that speed as cold, it's not actually colder at all.",
     "en"),
    ("Salt water buoyancy",
     "People float more easily in salt water than in fresh water because dissolved salt makes the water denser. That extra density means the same body needs to displace less water to stay afloat.",
     "Why is it easier to float in the ocean than in a pool?",
     "Salt water is simply denser than fresh water, so it pushes back harder against your body. That's the whole secret behind floating so easily at the beach.",
     "en"),

    # --- Zeit / Kalender ---
    ("Schaltjahr",
     "Ein Schaltjahr hat einen zusätzlichen Tag, den 29. Februar, weil ein Erdjahr eigentlich etwa 365,25 Tage dauert. Ohne diesen Ausgleich würde sich der Kalender langsam gegen die Jahreszeiten verschieben.",
     "Warum gibt es eigentlich Schaltjahre?",
     "Weil ein echtes Erdjahr nicht ordentlich 365 Tage hat, sondern ein Viertel Tag mehr. Der 29. Februar gleicht das aus, sonst würde sich unser Kalender langsam von den Jahreszeiten verabschieden.",
     "de"),
    ("Zeitzonen",
     "Zeitzonen gibt es, weil die Erde sich dreht und die Sonne deshalb nicht überall gleichzeitig am höchsten Punkt steht. Weltweit gibt es rund 24 Haupt-Zeitzonen, orientiert an den Längengraden.",
     "Warum gibt es eigentlich überhaupt Zeitzonen?",
     "Weil die Sonne nicht gleichzeitig überall am höchsten Punkt steht, die Erde dreht sich ja. Rund 24 Zeitzonen teilen die Welt dafür grob entlang der Längengrade auf.",
     "de"),
    ("Erdrotation",
     "Ein Tag dauert rund 24 Stunden, weil die Erde etwa so lange braucht, um sich einmal um die eigene Achse zu drehen. Genau genommen sind es knapp vier Minuten weniger, kleine Unterschiede gleicht man gelegentlich über Schaltsekunden aus.",
     "Warum hat ein Tag eigentlich 24 Stunden?",
     "Weil die Erde ziemlich genau so lange für eine Umdrehung um sich selbst braucht. Nicht perfekt exakt übrigens, ein paar Minuten Differenz gleichen wir hin und wieder mit Schaltsekunden aus.",
     "de"),
    ("Sommerzeit",
     "Die Sommerzeit wurde eingeführt, um Tageslicht besser zu nutzen und Energie zu sparen, ursprünglich im Ersten Weltkrieg. In Europa werden die Uhren dafür im Frühjahr eine Stunde vor- und im Herbst wieder zurückgestellt.",
     "Warum stellen wir eigentlich die Uhr im Frühling um?",
     "Ursprünglich ging es um Energiesparen, damit das Tageslicht abends länger genutzt wird, die Idee stammt sogar aus dem Ersten Weltkrieg. Bis heute drehen wir deshalb zweimal im Jahr an der Uhr.",
     "de"),
    ("Gregorianischer Kalender",
     "Der heute gebräuchliche Kalender geht auf eine Reform von Papst Gregor dem Dreizehnten im Jahr 1582 zurück. Er ersetzte den älteren julianischen Kalender, der sich über die Jahrhunderte leicht gegen die Jahreszeiten verschoben hatte.",
     "Woher kommt eigentlich unser Kalender?",
     "Von einer Reform aus dem Jahr 1582, angestoßen von Papst Gregor dem Dreizehnten. Davor lief der alte Kalender den Jahreszeiten über die Jahrhunderte langsam davon.",
     "de"),
    ("Jahreszeiten",
     "Die Jahreszeiten entstehen, weil die Erdachse leicht geneigt ist, um etwa 23 Grad. Dadurch bekommt mal die Nord-, mal die Südhalbkugel mehr direktes Sonnenlicht, während die Erde die Sonne umkreist.",
     "Warum gibt es eigentlich Jahreszeiten?",
     "Die Erdachse steht schief, etwa 23 Grad geneigt, und dadurch bekommt mal die eine, mal die andere Erdhälfte mehr Sonne ab. Nicht die Entfernung zur Sonne macht den Unterschied, sondern dieser Neigungswinkel.",
     "de"),
    ("Sieben-Tage-Woche",
     "Die Sieben-Tage-Woche geht vermutlich auf die alten Babylonier zurück, die sich an den sieben damals bekannten Himmelskörpern orientierten: Sonne, Mond und fünf sichtbare Planeten. Viele Sprachen tragen diese Namen bis heute in ihren Wochentagen.",
     "Warum hat eine Woche eigentlich sieben Tage?",
     "Vermutlich wegen den alten Babyloniern, die kannten genau sieben Himmelskörper: Sonne, Mond und fünf Planeten. Guck dir mal die Wochentagsnamen an, die Spuren davon stecken heute noch drin.",
     "de"),
    ("Atomuhr",
     "Eine Sekunde wird heute nicht mehr über die Erddrehung definiert, sondern über die extrem gleichmäßigen Schwingungen von Cäsium-Atomen. Atomuhren sind so genau, dass sie über Millionen Jahre nur um wenige Sekunden abweichen.",
     "Wie genau ist eigentlich eine Atomuhr?",
     "Verrückt genau: Über Millionen Jahre würde sie nur um ein paar Sekunden daneben liegen. Die zählt nämlich nicht die Erddrehung, sondern die Schwingungen von Cäsium-Atomen.",
     "de"),
    ("Datumsgrenze",
     "Die internationale Datumsgrenze verläuft ungefähr entlang des 180. Längengrads mitten im Pazifik. Wer sie überquert, springt je nach Richtung einen Kalendertag vor oder zurück.",
     "Was ist eigentlich die Datumsgrenze?",
     "Eine gedachte Linie mitten im Pazifik, ungefähr beim 180. Längengrad. Überquerst du sie, springt das Datum plötzlich einen ganzen Tag vor oder zurück, je nach Richtung.",
     "de"),
    ("Schaltsekunde",
     "Eine Schaltsekunde gleicht winzige Unregelmäßigkeiten in der Erdrotation aus, damit Atomzeit und tatsächliche Tageslänge nicht auseinanderdriften. Sie wird unregelmäßig eingefügt, meist am 30. Juni oder 31. Dezember.",
     "Was ist eigentlich eine Schaltsekunde?",
     "Ein winziger Zeitausgleich, weil sich die Erde nicht ganz gleichmäßig dreht. Alle paar Jahre wird dafür irgendwo im Kalender eine einzelne Sekunde nachgeschoben, meist im Juni oder Dezember.",
     "de"),
    ("Sundial",
     "A sundial tells time using the shadow of a raised pointer that moves as the sun crosses the sky over the day. It's one of the oldest known instruments for measuring time, used thousands of years ago.",
     "How does a sundial actually work?",
     "Just a stick and its shadow, really, the shadow swings around as the sun moves across the sky. People were reading time off shadows thousands of years before clocks existed.",
     "en"),
    ("Equinox",
     "An equinox happens twice a year, when day and night are almost exactly equal length nearly everywhere on Earth. It marks the astronomical start of spring or autumn, depending on the hemisphere and season.",
     "What actually happens on the equinox?",
     "Day and night come out almost perfectly equal, everywhere on Earth, just for that one day. It's the quiet little hinge where one season tips into the next.",
     "en"),
    ("Easter date",
     "Easter's date moves every year because it follows the moon rather than a fixed calendar day. It falls on the first Sunday after the first full moon following the spring equinox.",
     "Why does Easter fall on a different date every year?",
     "Because it's tied to the moon, not a fixed date, the first Sunday after the first full moon past the spring equinox. A calendar holiday that still quietly follows the sky.",
     "en"),
]
